# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  schedule:
        - cron: '15 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run app
      run: npm install
    - run: node app.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        TG_ID: ${{secrets.TG_ID}}
        TG_TOKEN: ${{secrets.TG_TOKEN}}
